engines:
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml
  eslint:
    enabled: true
  duplication:
    enabled: true
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  identical-code:
    enabled: false